version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 2.7
      java: corretto11
  build:
    commands:
      - /bin/bash ./javabuilder-authorizer/build.sh
      - /bin/bash ./org-code-javabuilder/build.sh
      - aws cloudformation package --template-file template.yml --s3-bucket cf-templates-18voktsbke3mi-us-east-1 --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
